version: '3'

services:
  node1:
    image: deeterd/cirquity
    container_name: cirqtest-node1
    volumes:
      - ../cirquityd:/var/lib/cirquityd/
    networks:
      testnet:
        ipv4_address: 172.16.76.11

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24
          